spring:
  application:
    name: eureka-server-clustered
  profiles: peer1
server:
  port: 8761
  context-path: /graducation
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:123456@peer2:8762/graducation/eureka/,http://root:123456@peer3:8763/graducation/eureka/
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456

---

spring:
  application:
    name: eureka-server-clustered
  profiles: peer2
server:
  port: 8762
  context-path: /graducation
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:123456@peer1:8761/graducation/eureka/,http://root:123456@peer3:8763/graducation/eureka/
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456


---

spring:
  application:
    name: eureka-server-clustered
  profiles: peer3
server:
  port: 8763
  context-path: /graducation
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:123456@peer1:8761/graducation/eureka/,http://root:123456@peer2:8762/graducation/eureka/
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456
logging:
  level: debug

